### ISSUE TITLE
Support for 28mm trays

### ISSUE THREAD

**Issue by abijango** [fidoriel/Mini-Tray#3]
Hi,

I have been trying to figure out how to add 28mm base support. Is it possible to add that?

**Comment by fidoriel** [comment]
Yes it is possible, but the codebase is not greate, I know. It is just code dublication at some points. Since years I wanted to refactor it, but originally I ran into OpenSCAD limitations, which I dont know how to fix. I will throw an simple example together.

**Comment by fidoriel** [comment]
you may have a look at it, do a test if it works for you and let me know
